#!/bin/bash

# Before this will work, you need to have XCode and the XCode command line tools installed
# > xcode-select --install

# Install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

# Configure homebrew
brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask

# Install gui apps
brew cask install adium
brew cask install alfred
brew cask install bitcasa
brew cask install caffeine
brew cask install dropbox
brew cask install evernote
brew cask install flash
brew cask install gas-mask
brew cask install google-chrome
brew cask install iterm2
brew cask install node
brew cask install silverlight
brew cask install Skype
brew cask install spectacle
brew cask install sublime-text
brew cask install vlc
brew cask install witch

# Install non-guis
brew install mackup
npm install nvm

# Install rvm
ruby -e "$(curl -sSL https://get.rvm.io | bash)"

# Give alfred a chance to see cask apps
brew cask alfred link

# Add a 'sublime' command
ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime
