#!/usr/bin/env ruby

# Get the directory where this script is located
DIR = File.dirname(File.realpath(__FILE__))

Dir.chdir(DIR) do
  # Handle --update flag to run hygiene instead of full setup
  if ARGV.include?('--update')
    puts "Running system hygiene..."
    exec "bin/hygiene"
  else
    require_relative 'lib/sudo_manager'
    
    if SudoManager.ensure_sudo_available
      system "bin/full_setup #{ARGV.join(' ')}"
    else
      puts "Setup cancelled - administrator authentication required."
      exit 1
    end
  end
end

