#!/usr/bin/env ruby

# Get the directory where this script is located
DIR = File.dirname(File.realpath(__FILE__))

Dir.chdir(DIR) do
  require_relative 'lib/sudo_manager'
  
  if SudoManager.ensure_sudo_available
    system "bin/full_setup #{ARGV.join(' ')}"
  else
    puts "Setup cancelled - administrator authentication required."
    exit 1
  end
end

