# Homebrew packages (brew)
brew "asdf"
brew "bat"
brew "diff-so-fancy"
brew "eza"
brew "gifsicle"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "hub"
brew "imagemagick"
brew "mas"  # Required for Mac App Store apps
brew "pure"
brew "pyenv"
brew "thefuck"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Homebrew casks
cask "1password-cli"
cask "alfred"
cask "arc"
cask "caffeine"
cask "cardhop"
cask "cursor"
cask "dropbox"
cask "elgato-stream-deck"
cask "flux"
cask "google-drive"
cask "hazel"
cask "iterm2"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "moom"
cask "mos"
cask "obsidian"
cask "renamer"
cask "shottr"
cask "spotify"
cask "superhuman"
cask "vimcal"
cask "visual-studio-code"

# Mac App Store apps
mas "CARROTweather", id: 993487541
mas "Meeter", id: 1510445899
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Toolkit for YNAB", id: 1592912837 