name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install shellcheck bats-core
      - name: Run all tests
        run: ./tests/run.sh
